name: eurobot-2026-navigation2

services:
  navigation-build:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERID: "${USER_UID:-1000}"
        USERGID: "${USER_UID:-1000}"
        ENABLE_VNC: "false"
    image: &IMG_NAME justinshih0918/eurobot2026-nav2-envs:machine-amd64
    container_name: navigation2-build
    command: &CMD_BUILD /bin/bash -c "cd /home/user/Eurobot-2026-Navigation2-ws && colcon build"
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stop_grace_period: &STOP_GRACE_PERIOD 1s
    deploy: &DEPLOY_SETTING
      # resources:
      #   limits:
      #     cpus: '2'

    # mount our navigation code & share directory
    volumes: &VOLUMES
      - ../..:/home/user/Eurobot-2026-Navigation2-ws
      - /home/share:/home/share
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority 
      - /dev:/dev

    working_dir: &WORKING_DIR
      /home/user/Eurobot-2026-Navigation2-ws

    environment: &ENV
      # - DISPLAY=${DISPLAY}  # Set display environment variable
      - RCUTILS_COLORIZED_OUTPUT=1
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - USERID=${USER_UID:-1000}
      - USERGID=${USER_UID:-1000}
      - USERNAME=user

  navigation-develop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERID: "${USER_UID:-1000}"
        USERGID: "${USER_UID:-1000}"
        ENABLE_VNC: "false"
    image: *IMG_NAME 
    container_name: navigation2-dev
    command: &CMD_DEVELOP /bin/bash
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stop_grace_period: *STOP_GRACE_PERIOD
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: *ENV
    

  navigation-run:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERID: "${USER_UID:-1000}"
        USERGID: "${USER_UID:-1000}"
        ENABLE_VNC: "false"
    image: *IMG_NAME 
    container_name: navigation2-run
    command: &CMD_RUN /bin/bash -c "cd /home/user/Eurobot-2026-Navigation2-ws && source install/local_setup.bash && ros2 launch navigation2_run real_launch.py 2>&1 | tee /home/user/Eurobot-2026-Navigation2-ws/nav2_log.txt"
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stop_grace_period: *STOP_GRACE_PERIOD
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: *ENV

  navigation-vnc:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        USERID: "${USER_UID:-1000}"
        USERGID: "${USER_UID:-1000}"
        ENABLE_VNC: "true"
    image: justinshih0918/eurobot2026-nav2-envs:vnc
    container_name: navigation2-vnc
    hostname: navigation2-vnc
    command: /usr/local/bin/start-vnc.sh
    tty: true
    ports:
      - "${VNC_PORT:-5901}:5901"
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD:-ros}
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
      - RCUTILS_COLORIZED_OUTPUT=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - USERID=${USER_UID:-1000}
      - USERGID=${USER_UID:-1000}
      - USERNAME=user
    volumes:
      - /home/share:/home/share
      - ../..:/home/user/Eurobot-2026-Navigation2-ws
      - /dev:/dev
    working_dir: /home/user/Eurobot-2026-Navigation2-ws
    ipc: host
    privileged: true
    stdin_open: true
    stop_grace_period: *STOP_GRACE_PERIOD

volumes:
  ros_x11:
    external: true
    name: ros_x11