/**:
  ros__parameters:
    robot_name: "White"
    
    # Timing Configuration
    time_rate: 100          # Timer rate in microseconds
    game_time: 100          # Total game time in seconds
    sima_tick_threshold: 85 # Seconds before sima starts
    group_num: 5            # Total number of groups (including index 0)
    
    # Start Pose Configuration
    # Format: [x, y, yaw_in_radians]
    
    # Configuration for Blue Team match
    blue_team:
      start_pose: [2.7, 1.775, 0.0]
      
    # Configuration for Yellow Team match
    yellow_team:
      start_pose: [0.3, 1.775, 0.0]